grafana:
  image: grafana/grafana:latest
  ports:
    - "3000:3000"
  volumes:
    - ./dist:/var/lib/grafana/plugins/grafana/percona-gif-panel
    - ./provisioning/datasources:/etc/grafana/provisioning/datasources
  environment:
    - TERM=linux